version: '3'

tasks:
  lint:
    desc: Runs Golang linters
    cmds:
      - GOFLAGS="-buildvcs=false" golangci-lint run --timeout=5m
    sources:
      - ./**/*.go
      - ./.golangci.yml
    method: checksum

  unit-test:
    desc: Runs Golang unit tests
    cmds:
      - go test -v ./...

  integration-test:
    desc: Runs Golang integration tests
    cmds:
      - go test -tags=integration ./tests/integration
