version: '3'

tasks:
  lint:
    desc: Runs linters
    cmds:
      - GOFLAGS="-buildvcs=false" golangci-lint run --timeout=5m
    sources:
      - ./**/*.go
      - ./.golangci.yml
    method: checksum

  unittests:
    desc: Runs unit tests
    cmds:
      - go test -v ./tests/unit/...

  integrationtests:
    desc: Runs integration tests
    cmds:
      - go test -tags=integration -count=1 ./tests/integration/...

  docker-build:
    desc: Builds Docker image
    cmds:
      - docker build -t corbado-go:latest .
    sources:
      - ./Dockerfile
    method: checksum

  generate-openapi:
    deps:
      - docker-build
    desc: Generates OpenAPI entities and clients
    cmds:
      - docker run -it -v $(pwd):/app corbado-go:latest scripts/generate-openapi.sh pkg/generated
