name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: "./.github/workflows/ci_test.yml"
    secrets: inherit

  lint:
    uses: "./.github/workflows/ci_lint.yml"
    secrets: inherit
