name: tests

on:
  push:
    # Matches all branches including / in name
    branches: '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    uses: "./.github/workflows/ci_unittests.yml"
    secrets: inherit

  integrationtests:
    uses: "./.github/workflows/ci_integrationtests.yml"
    secrets: inherit

  lint:
    uses: "./.github/workflows/ci_lint.yml"
    secrets: inherit
