name: tests

on:
  push:
    branches: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    uses: "./.github/workflows/ci_unit_test.yml"
    secrets: inherit

  integration-test:
    uses: "./.github/workflows/ci_integration_test.yml"
    secrets: inherit

  lint:
    uses: "./.github/workflows/ci_lint.yml"
    secrets: inherit
