name: integration-test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - env:
          CORBADO_BACKEND_API: ${{ secrets.CORBADO_BACKEND_API }}
          CORBADO_PROJECT_ID: ${{ secrets.CORBADO_PROJECT_ID }}
          CORBADO_API_SECRET: ${{ secrets.CORBADO_API_SECRET }}
        run: go test -tags=integration ./tests/integration/...