name: lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.55.2
          args: --timeout 5m
