name: unittests

on:
  workflow_call:

jobs:
  unittests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
          
      - name: Run unit tests
        run: go test tests/unit/...
